name: Publish release to PyPI and RCs to TestPyPI
on: push

jobs:
  build-n-publish:
    name: Build and publish distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pypa/build
      run: python3 -m pip install build --user

    - name: Patch the RC version number to current timestamp
      if: github.ref != 'refs/heads/master'
      run: >-
        sed -i -E s/version=\'[0-9].[0-9]+.[0-9]+/version=\'`date +%s`/ setup.py

    - name: Build a binary wheel and a source tarball
      run: >-
        python3 -m build --sdist --wheel --outdir dist/ .

    - name: Publish distribution 📦 to Test PyPI
      if: startsWith(github.ref, 'refs/heads/0_')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository-url: https://test.pypi.org/legacy/

#    - name: Publish distribution 📦 to PyPI
#      if: startsWith(github.ref, 'refs/heads/master')
#      uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#        password: ${{ secrets.PYPI_API_TOKEN }}
